// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  callId: __t.u64().primaryKey().name("call_id"),
  agentName: __t.string().name("agent_name"),
  status: __t.string(),
  currentTask: __t.string().name("current_task"),
  updatedAt: __t.timestamp().name("updated_at"),
});
