// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  callId: __t.u64().name("call_id"),
  actionType: __t.string().name("action_type"),
  reasoningSummary: __t.string().name("reasoning_summary"),
  actionValue: __t.string().name("action_value"),
  confidence: __t.f64(),
  status: __t.string(),
  timestamp: __t.timestamp(),
});
