// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.string().name("user_id"),
  companyName: __t.string().name("company_name"),
  phoneNumber: __t.string().name("phone_number"),
  userGoal: __t.string().name("user_goal"),
  userPhoneNumber: __t.string().name("user_phone_number"),
  status: __t.string(),
  currentMenuContext: __t.string().name("current_menu_context"),
  lastActionSummary: __t.string().name("last_action_summary"),
  humanConfidence: __t.f64().name("human_confidence"),
  errorMessage: __t.string().name("error_message"),
  mode: __t.string(),
  source: __t.string(),
  demo: __t.bool(),
  cancelRequested: __t.bool().name("cancel_requested"),
  supportCallSid: __t.string().name("support_call_sid"),
  userCallSid: __t.string().name("user_call_sid"),
  startedAt: __t.timestamp().name("started_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  holdStartedAt: __t.option(__t.timestamp()).name("hold_started_at"),
  humanDetectedAt: __t.option(__t.timestamp()).name("human_detected_at"),
  connectedAt: __t.option(__t.timestamp()).name("connected_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
