// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AppendCallEventReducer from "./append_call_event_reducer";
import AppendTaskEventReducer from "./append_task_event_reducer";
import AppendTranscriptReducer from "./append_transcript_reducer";
import ApproveTaskReducer from "./approve_task_reducer";
import CancelCallReducer from "./cancel_call_reducer";
import CancelTaskReducer from "./cancel_task_reducer";
import ClaimCallReducer from "./claim_call_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import CompleteCallReducer from "./complete_call_reducer";
import CompleteTaskReducer from "./complete_task_reducer";
import FailCallReducer from "./fail_call_reducer";
import FailTaskReducer from "./fail_task_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import MarkHumanDetectedReducer from "./mark_human_detected_reducer";
import MarkUserConnectedReducer from "./mark_user_connected_reducer";
import RecordAgentActionReducer from "./record_agent_action_reducer";
import RegisterOrchestratorReducer from "./register_orchestrator_reducer";
import RequestCallReducer from "./request_call_reducer";
import RequestTaskReducer from "./request_task_reducer";
import SetAgentStatusReducer from "./set_agent_status_reducer";
import SetCallSidsReducer from "./set_call_sids_reducer";
import UpdateCallStatusReducer from "./update_call_status_reducer";
import UpdateHumanConfidenceReducer from "./update_human_confidence_reducer";
import UpdateTaskReducer from "./update_task_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentStatusRow from "./agent_status_table";
import CallActionRow from "./call_action_table";
import CallEventRow from "./call_event_table";
import CallSessionRow from "./call_session_table";
import OrchestratorRow from "./orchestrator_table";
import SupportTaskRow from "./support_task_table";
import TaskEventRow from "./task_event_table";
import TranscriptSegmentRow from "./transcript_segment_table";
import UserContextRow from "./user_context_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agentStatus: __table({
    name: 'agent_status',
    indexes: [
      { accessor: 'callId', name: 'agent_status_call_id_idx_btree', algorithm: 'btree', columns: [
        'callId',
      ] },
    ],
    constraints: [
      { name: 'agent_status_call_id_key', constraint: 'unique', columns: ['callId'] },
    ],
  }, AgentStatusRow),
  callAction: __table({
    name: 'call_action',
    indexes: [
      { accessor: 'callId', name: 'call_action_call_id_idx_btree', algorithm: 'btree', columns: [
        'callId',
      ] },
      { accessor: 'id', name: 'call_action_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'call_action_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CallActionRow),
  callEvent: __table({
    name: 'call_event',
    indexes: [
      { accessor: 'callId', name: 'call_event_call_id_idx_btree', algorithm: 'btree', columns: [
        'callId',
      ] },
      { accessor: 'dedupeKey', name: 'call_event_dedupe_key_idx_btree', algorithm: 'btree', columns: [
        'dedupeKey',
      ] },
      { accessor: 'id', name: 'call_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'call_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CallEventRow),
  callSession: __table({
    name: 'call_session',
    indexes: [
      { accessor: 'id', name: 'call_session_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'call_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CallSessionRow),
  orchestrator: __table({
    name: 'orchestrator',
    indexes: [
      { accessor: 'id', name: 'orchestrator_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'orchestrator_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrchestratorRow),
  supportTask: __table({
    name: 'support_task',
    indexes: [
      { accessor: 'id', name: 'support_task_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'support_task_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SupportTaskRow),
  taskEvent: __table({
    name: 'task_event',
    indexes: [
      { accessor: 'id', name: 'task_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'taskId', name: 'task_event_task_id_idx_btree', algorithm: 'btree', columns: [
        'taskId',
      ] },
    ],
    constraints: [
      { name: 'task_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskEventRow),
  transcriptSegment: __table({
    name: 'transcript_segment',
    indexes: [
      { accessor: 'callId', name: 'transcript_segment_call_id_idx_btree', algorithm: 'btree', columns: [
        'callId',
      ] },
      { accessor: 'id', name: 'transcript_segment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'transcript_segment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TranscriptSegmentRow),
  userContext: __table({
    name: 'user_context',
    indexes: [
      { accessor: 'callId', name: 'user_context_call_id_idx_btree', algorithm: 'btree', columns: [
        'callId',
      ] },
      { accessor: 'id', name: 'user_context_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'user_context_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserContextRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("append_call_event", AppendCallEventReducer),
  __reducerSchema("append_task_event", AppendTaskEventReducer),
  __reducerSchema("append_transcript", AppendTranscriptReducer),
  __reducerSchema("approve_task", ApproveTaskReducer),
  __reducerSchema("cancel_call", CancelCallReducer),
  __reducerSchema("cancel_task", CancelTaskReducer),
  __reducerSchema("claim_call", ClaimCallReducer),
  __reducerSchema("claim_task", ClaimTaskReducer),
  __reducerSchema("complete_call", CompleteCallReducer),
  __reducerSchema("complete_task", CompleteTaskReducer),
  __reducerSchema("fail_call", FailCallReducer),
  __reducerSchema("fail_task", FailTaskReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("mark_human_detected", MarkHumanDetectedReducer),
  __reducerSchema("mark_user_connected", MarkUserConnectedReducer),
  __reducerSchema("record_agent_action", RecordAgentActionReducer),
  __reducerSchema("register_orchestrator", RegisterOrchestratorReducer),
  __reducerSchema("request_call", RequestCallReducer),
  __reducerSchema("request_task", RequestTaskReducer),
  __reducerSchema("set_agent_status", SetAgentStatusReducer),
  __reducerSchema("set_call_sids", SetCallSidsReducer),
  __reducerSchema("update_call_status", UpdateCallStatusReducer),
  __reducerSchema("update_human_confidence", UpdateHumanConfidenceReducer),
  __reducerSchema("update_task", UpdateTaskReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

