// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  identity: __t.identity(),
  mode: __t.string(),
  demoMode: __t.bool().name("demo_mode"),
  reasoning: __t.string(),
  voice: __t.string(),
  demoSupportNumber: __t.string().name("demo_support_number"),
  demoUserNumber: __t.string().name("demo_user_number"),
  version: __t.string(),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
});
