// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  mode: __t.string(),
  demoMode: __t.bool(),
  reasoning: __t.string(),
  voice: __t.string(),
  demoSupportNumber: __t.string(),
  demoUserNumber: __t.string(),
  version: __t.string(),
};
