// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  companyName: __t.string(),
  phoneNumber: __t.string(),
  userGoal: __t.string(),
  userPhoneNumber: __t.string(),
  userContext: __t.string(),
  source: __t.string(),
  demo: __t.bool(),
};
