// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.string().name("user_id"),
  channel: __t.string(),
  provider: __t.string(),
  query: __t.string(),
  paramsJson: __t.string().name("params_json"),
  status: __t.string(),
  step: __t.string(),
  summary: __t.string(),
  result: __t.string(),
  errorMessage: __t.string().name("error_message"),
  approveRequested: __t.bool().name("approve_requested"),
  cancelRequested: __t.bool().name("cancel_requested"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
