// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentStatus = __t.object("AgentStatus", {
  callId: __t.u64(),
  agentName: __t.string(),
  status: __t.string(),
  currentTask: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AgentStatus = __Infer<typeof AgentStatus>;

export const CallAction = __t.object("CallAction", {
  id: __t.u64(),
  callId: __t.u64(),
  actionType: __t.string(),
  reasoningSummary: __t.string(),
  actionValue: __t.string(),
  confidence: __t.f64(),
  status: __t.string(),
  timestamp: __t.timestamp(),
});
export type CallAction = __Infer<typeof CallAction>;

export const CallEvent = __t.object("CallEvent", {
  id: __t.u64(),
  callId: __t.u64(),
  timestamp: __t.timestamp(),
  type: __t.string(),
  actor: __t.string(),
  title: __t.string(),
  description: __t.string(),
  metadata: __t.string(),
  dedupeKey: __t.string(),
});
export type CallEvent = __Infer<typeof CallEvent>;

export const CallSession = __t.object("CallSession", {
  id: __t.u64(),
  userId: __t.string(),
  companyName: __t.string(),
  phoneNumber: __t.string(),
  userGoal: __t.string(),
  userPhoneNumber: __t.string(),
  status: __t.string(),
  currentMenuContext: __t.string(),
  lastActionSummary: __t.string(),
  humanConfidence: __t.f64(),
  errorMessage: __t.string(),
  mode: __t.string(),
  source: __t.string(),
  demo: __t.bool(),
  cancelRequested: __t.bool(),
  supportCallSid: __t.string(),
  userCallSid: __t.string(),
  startedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  holdStartedAt: __t.option(__t.timestamp()),
  humanDetectedAt: __t.option(__t.timestamp()),
  connectedAt: __t.option(__t.timestamp()),
  endedAt: __t.option(__t.timestamp()),
});
export type CallSession = __Infer<typeof CallSession>;

export const Orchestrator = __t.object("Orchestrator", {
  id: __t.u32(),
  identity: __t.identity(),
  mode: __t.string(),
  demoMode: __t.bool(),
  reasoning: __t.string(),
  voice: __t.string(),
  demoSupportNumber: __t.string(),
  demoUserNumber: __t.string(),
  version: __t.string(),
  lastHeartbeat: __t.timestamp(),
});
export type Orchestrator = __Infer<typeof Orchestrator>;

export const TranscriptSegment = __t.object("TranscriptSegment", {
  id: __t.u64(),
  callId: __t.u64(),
  speakerType: __t.string(),
  text: __t.string(),
  confidence: __t.f64(),
  createdAt: __t.timestamp(),
});
export type TranscriptSegment = __Infer<typeof TranscriptSegment>;

export const UserContext = __t.object("UserContext", {
  id: __t.u64(),
  callId: __t.u64(),
  source: __t.string(),
  label: __t.string(),
  value: __t.string(),
});
export type UserContext = __Infer<typeof UserContext>;

export const WatchdogTimer = __t.object("WatchdogTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WatchdogTimer = __Infer<typeof WatchdogTimer>;

