// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendCallEventReducer from "../append_call_event_reducer";
import AppendTaskEventReducer from "../append_task_event_reducer";
import AppendTranscriptReducer from "../append_transcript_reducer";
import ApproveTaskReducer from "../approve_task_reducer";
import CancelCallReducer from "../cancel_call_reducer";
import CancelTaskReducer from "../cancel_task_reducer";
import ClaimCallReducer from "../claim_call_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompleteCallReducer from "../complete_call_reducer";
import CompleteTaskReducer from "../complete_task_reducer";
import FailCallReducer from "../fail_call_reducer";
import FailTaskReducer from "../fail_task_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import MarkHumanDetectedReducer from "../mark_human_detected_reducer";
import MarkUserConnectedReducer from "../mark_user_connected_reducer";
import RecordAgentActionReducer from "../record_agent_action_reducer";
import RegisterOrchestratorReducer from "../register_orchestrator_reducer";
import RequestCallReducer from "../request_call_reducer";
import RequestTaskReducer from "../request_task_reducer";
import SetAgentStatusReducer from "../set_agent_status_reducer";
import SetCallSidsReducer from "../set_call_sids_reducer";
import UpdateCallStatusReducer from "../update_call_status_reducer";
import UpdateHumanConfidenceReducer from "../update_human_confidence_reducer";
import UpdateTaskReducer from "../update_task_reducer";

export type AppendCallEventParams = __Infer<typeof AppendCallEventReducer>;
export type AppendTaskEventParams = __Infer<typeof AppendTaskEventReducer>;
export type AppendTranscriptParams = __Infer<typeof AppendTranscriptReducer>;
export type ApproveTaskParams = __Infer<typeof ApproveTaskReducer>;
export type CancelCallParams = __Infer<typeof CancelCallReducer>;
export type CancelTaskParams = __Infer<typeof CancelTaskReducer>;
export type ClaimCallParams = __Infer<typeof ClaimCallReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompleteCallParams = __Infer<typeof CompleteCallReducer>;
export type CompleteTaskParams = __Infer<typeof CompleteTaskReducer>;
export type FailCallParams = __Infer<typeof FailCallReducer>;
export type FailTaskParams = __Infer<typeof FailTaskReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type MarkHumanDetectedParams = __Infer<typeof MarkHumanDetectedReducer>;
export type MarkUserConnectedParams = __Infer<typeof MarkUserConnectedReducer>;
export type RecordAgentActionParams = __Infer<typeof RecordAgentActionReducer>;
export type RegisterOrchestratorParams = __Infer<typeof RegisterOrchestratorReducer>;
export type RequestCallParams = __Infer<typeof RequestCallReducer>;
export type RequestTaskParams = __Infer<typeof RequestTaskReducer>;
export type SetAgentStatusParams = __Infer<typeof SetAgentStatusReducer>;
export type SetCallSidsParams = __Infer<typeof SetCallSidsReducer>;
export type UpdateCallStatusParams = __Infer<typeof UpdateCallStatusReducer>;
export type UpdateHumanConfidenceParams = __Infer<typeof UpdateHumanConfidenceReducer>;
export type UpdateTaskParams = __Infer<typeof UpdateTaskReducer>;

